"""add_image_fields_to_body_types

Revision ID: 06c9ff4c2d63
Revises: 6ce37902fdd5
Create Date: 2026-04-07 23:45:17.688619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06c9ff4c2d63'
down_revision: Union[str, Sequence[str], None] = '6ce37902fdd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('body_types', sa.Column('image_filename', sa.String(), nullable=True))
    op.add_column('body_types', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('body_types', sa.Column('thumbnail_url', sa.String(), nullable=True))
    op.add_column('body_types', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('body_types', 'is_active')
    op.drop_column('body_types', 'thumbnail_url')
    op.drop_column('body_types', 'image_url')
    op.drop_column('body_types', 'image_filename')
    # ### end Alembic commands ###
