"""create wardrobes table

Revision ID: 072cca75aa3e
Revises: 8d83e6f77755
Create Date: 2026-04-06 20:07:59.833157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '072cca75aa3e'
down_revision: Union[str, Sequence[str], None] = '8d83e6f77755'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wardrobes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('image_filename', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('subcategory', sa.String(), nullable=True),
    sa.Column('color', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('pattern', sa.String(), nullable=True),
    sa.Column('style_tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('occasion_tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('season', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('fabric', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.Column('times_worn', sa.Integer(), nullable=True),
    sa.Column('last_worn_at', sa.DateTime(), nullable=True),
    sa.Column('ai_description', sa.String(), nullable=True),
    sa.Column('ai_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wardrobes')
    # ### end Alembic commands ###
