"""Make wardrobe category nullable

Revision ID: 51841880a477
Revises: 072cca75aa3e
Create Date: 2026-04-06 20:11:06.821615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51841880a477'
down_revision: Union[str, Sequence[str], None] = '072cca75aa3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wardrobes', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wardrobes', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
