"""add_category_and_tags_to_styles

Revision ID: 6ce37902fdd5
Revises: 798ab9fe8d4c
Create Date: 2026-04-07 22:51:22.312429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ce37902fdd5'
down_revision: Union[str, Sequence[str], None] = '798ab9fe8d4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('styles', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('styles', sa.Column('tags', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('styles', 'tags')
    op.drop_column('styles', 'category')
    # ### end Alembic commands ###
