"""add brands table

Revision ID: 7384eb703ab3
Revises: 8239b9b6565c
Create Date: 2026-04-23 10:24:57.467065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7384eb703ab3'
down_revision: Union[str, Sequence[str], None] = '8239b9b6565c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wardrobes', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('wardrobes', 'is_favorite',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('wardrobes', 'times_worn',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('wardrobes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('wardrobes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wardrobes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('wardrobes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('wardrobes', 'times_worn',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('wardrobes', 'is_favorite',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('wardrobes', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
