"""add skin_tone_id to profiles

Revision ID: 8046fd548f0b
Revises: 472df353f5c4
Create Date: 2026-04-28 13:06:40.548330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8046fd548f0b'
down_revision: Union[str, Sequence[str], None] = '472df353f5c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skin_tones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hex', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skin_tones_id'), 'skin_tones', ['id'], unique=False)
    op.add_column('profiles', sa.Column('skin_tone_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'profiles', 'skin_tones', ['skin_tone_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.drop_column('profiles', 'skin_tone_id')
    op.drop_index(op.f('ix_skin_tones_id'), table_name='skin_tones')
    op.drop_table('skin_tones')
    # ### end Alembic commands ###
