"""Added logo tolerance field

Revision ID: ae155ea77b25
Revises: 0d542f4e65d9
Create Date: 2026-04-06 11:26:02.686207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae155ea77b25'
down_revision: Union[str, Sequence[str], None] = '0d542f4e65d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'budget')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('budget', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
