"""Add location to profiles

Revision ID: eb7c7c8c1290
Revises: e8e79941c83c
Create Date: 2026-04-06 12:57:36.368305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb7c7c8c1290'
down_revision: Union[str, Sequence[str], None] = 'e8e79941c83c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('location', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'location')
    # ### end Alembic commands ###
