"""add unique constraint to skin_tone name

Revision ID: f4507e25449a
Revises: 8046fd548f0b
Create Date: 2026-04-28 13:32:41.328136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4507e25449a'
down_revision: Union[str, Sequence[str], None] = '8046fd548f0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'skin_tones', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skin_tones', type_='unique')
    # ### end Alembic commands ###
